### ISSUE TITLE
different temperature readings.

### ISSUE THREAD

**Issue by wmala2** [adafruit/Adafruit_CircuitPython_MAX31856#21] opened 2022-08-21 14:13 UTC
I am running this code on a raspberry pi zero and I get two different results depending on which library I use. The thermocouple is in an ice water bath so I tend to trust the 31855 library result more.
![Screenshot 2022-08-21 101055](https://user-images.githubusercontent.com/104680760/185795174-130844fc-4061-43e6-b738-9decde05df2f.png)
![script](https://user-images.githubusercontent.com/104680760/185795229-2d08ca5c-bdc0-40e6-9a91-8d3c4aa0e87f.png)

**Comment by caternuson** [comment] 2022-08-21 15:44
Which breakout are you using? The MAX31855?
https://www.adafruit.com/product/269
or the MAX31856?
https://www.adafruit.com/product/3263

**Comment by wmala2** [comment] 2022-08-21 15:50
Sorry. I meant to say I'm using the breakout for the MAX31856.

**Comment by caternuson** [comment] 2022-08-21 16:01
What values do you get running the library example?
https://github.com/adafruit/Adafruit_CircuitPython_MAX31856/blob/main/examples/max31856_simpletest.py

**Comment by wmala2** [comment] 2022-08-21 16:22
I'll run those and get back to you

**Comment by wmala2** [comment] 2022-08-21 19:46
I took the thermocouple out of the water and still get the 0.5 reading with
the 31855 library so I guess there's no issue. Do you want me to remove the
issue or do you want to just close it out? Sorry for the false alarm.

**Comment by caternuson** [comment] 2022-08-21 20:10
OK to just close it if you think the issue is resolved.

**Closed as completed** 2022-08-21 21:50 UTC
